### PR TITLE
Reimplement storage and summarization for performance

### LINKED ISSUE #9: Performance on large data sets
First off, thank you for this very useful library.

I have recently used it to aggregate networks from Maxmind's `GeoLite2-City.mmdb` and noticed that runtime seems to increase exponentially, as the number of subnets increase. See the graph below:

routesum_performance

I have uploaded the code I used to measure this into a gist, which can be found here:
https://gist.github.com/stevemeier/ef0148cd466f4e7b4f73a9d3a57c7e79

I considered doing aggregations half-way through, but I am not sure if this is a good solution to the problem or if the algorithm could somehow be improved.

### PR DESCRIPTION
**Pull request by PatrickCronin**
This PR changes the fundamental way routes are stored and the route summarization is calculated.

Resolves #9.

### CODE REVIEW

**Comment by oschwald** [comment]
Have you considered just using a specialized binary tree like `mmdbwriter`? I'd guess that it would be faster, use less memory, and it would allow you to output the networks in order.

**Comment by PatrickCronin** [comment]
Hi @oschwald! I did consider a specialized binary tree. @rafl told me about the existence of radix trees, and this PR implements a radix-ish tree of radix 2 in [rstrie.go](https://github.com/PatrickCronin/routesum/blob/275dad598120ac382e150aac7ea52f9cfdeb83f3/pkg/routesum/rstrie/rstrie.go).  I haven't looked in detail at the structure implemented in mmdbwriter yet--I'll do that when things settle down a bit--but I'm pretty happy with the shape this one is taking. Does mmdbwriter do something better?

**Comment by oschwald** [comment]
I saw the radix tree implementation. Nice!

The `mmdbwriter` data structure is less sophisticated but fairly well adapted to this particular problem. It eliminates the need to store the bits separately and makes merging networks very simple.

**Comment by PatrickCronin** [comment]
I created 3 datasets to use for speed comparisons:

* All IPs in the GeoLite2 Country DB
* All IPs in the GeoLite2 City DB
* All IPs in the [DShield API's Intelfeed endpoint](https://www.dshield.org/api/#intelfeed)

See [mmdb-dump-networks](https://github.com/PatrickCronin/mmdb-dump-networks) and [dshield-intelfeed-ips](https://github.com/PatrickCronin/dshield-intelfeed-ips) for utilities created for the purpose of generating these datasets.

I used go `testing`'s built-in benchmarking functions to check the speed and memory performance of the old code vs the new code on these data sets.

| Source                      | Num IPs    | After Summing | Old Code (s)      | Old Code (MB Allocated) | Old Code (Heap MB at Full Structure) | New Code (s) | New Code (MB Allocated) | New Code (Heap MB at Full Structure) |
|-----------------------------|------------|---------------|-------------------|-------------------------|--------------------------------------|--------------|-------------------------|--------------------------------------|
| DShield API's Intelfeed IPs | 58,131     | 41,765        | 63                | 6615.66                 | 3.25                                 | 2.6          | 17.15                   | 8.06                                 |
| GeoLite2 Country Networks   | 1,843,336  | 96,325        | More than 3 hours | DNF*                    | DNF*                                 | 3.1          | 812.64                  | 29.59                                |
| GeoLite2 City Networks      | 15,530,913 | 96,325        | DNT*              | DNT*                    | DNT*                                 | 22.9         | 6637.09                 | 27.59                                |

`* DNF`: Ran for 3 hours and was killed by the testing platform. I could have overrode this even more, but I didn't see the need, as the new code processed the dataset in 3.1 seconds.
`* DNT`: Based on the performance of the old code on the previous dataset, and this being around 8 times larger, I didn't even try.

Based on the above, it's clear this PR greatly improves the speed and memory usage of the routesumming algorithm. #9 contains an illustration that makes performance of the original code look like it degrades exponentially as input increases, however the x-axis scale itself is essentially exponential so it's hard to determine whether it it actually exponential growth or just linear growth. I'll leave that analysis to another day.

The idea posed by @oschwald, i.e. to replace the radix-like trie with a binary tree, to not store any path-related information in the nodes themselves, but rather to derive it from the edges bewteen them, may yet prove to be an additional improvement. However based on the results above, the PR is good enough to merge currently.

**Pull request merged**
